export default () => ({
  name: "",
  description: "",
  todofullLabels: [],
  filters: {
    includeWithEmail: true,
    includeWithoutEmail: true,
    includeWithChats: true,
    includeWithSales: false,
    includeWithIDGenial: true,
    includeWithoutIDGenial: true,
    minSaleOrderCount: 0,
    minPosOrderCount: 0,
    minSalePosOrderCount: 0,
    salesTeams: [],
    rfmScores: [],
    campaignFilter: {
      type: null,
      campaigns: [],
      timeInterval: "any_time", 
    },
  },
  botIds: [],
  type: "static",
});
